name: Pipeline Diário - Barbearia

on:
  workflow_dispatch: # Permite rodar manualmente
  schedule:
    - cron: '0 11 * * *' # Roda todo dia às 08:00 AM (Horário de Brasília aprox. UTC-3)

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: 1. Extração (Sheets)
        run: python src/extract.py

      - name: 2. Transformação (dbt)
        run: |
          cd dbt_project
          dbt run --profiles-dir .
          # Opcional: dbt test --profiles-dir .

      - name: 3. Envio de Relatório
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python src/send_email.py